<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Shown as "Version" in the /appinfo response. -->
    <Version>1.0.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCore.AppInfo\AspNetCore.AppInfo.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.AppInfo.Environment\AspNetCore.AppInfo.Environment.csproj" />
  </ItemGroup>

</Project>
